#!/usr/bin/env bash
# tells
while IFS=":" -r username password uid gid info home shell
do
echo "The user $user is part of the $gid gang, lives in $homedir and rides $loginshell. $uid's place is protected by the passcode $pass, more info about the user here: $username_f"
done < "/etc/passwd"
