#!/usr/bin/env bash
#script displays that loops from 1 to 10 and on 4th iteration displays bad lucl, on 8th good luck, best school on others
i=1
while [ $i -le 10 ]
do
if [ $i -eq 4 ]; then
echo "bad luck"
i=$((i+1))
elif [ $i -eq 8 ]; then
echo "good luck"
i=$((i+1))
else
echo "Best School"
i=$((i+1))
fi
done
