#!/usr/bin/env bash
#script displays the time for 12 houres and 59 minutes
i=0
x=1
while [ $i -le 12 ]
do
    echo "Hour: $i"
    while [ $x -le 59 ]
    do
	echo $x
	x=$((x+1))
    done
    x=1
    i=$((i+1))
done
