#!/usr/bin/env bash
#script that configures an ubuntu server with the below reqs
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localgost\n8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts